### ISSUE TITLE
iPad Printing Issues

### ISSUE THREAD

**Issue by pastorjosh5142** [petereit/CheckinAir#29]
Hello. I'm having issues with iPads printing to the printer. We are using Checkin Air...we're all logged in and can check in children, but the Brother QL-810W just isn't being recognized as a printer. The settings say there is no printer attached. 

We use two iPad 4's with a Google WiFi network. At first I thought it might be a network connection issue as the router is downstairs...so I added a Mesh Node just down the hall from the iPads and we now have strong wifi for this network over the entire youth/children's wing of the church.

I have setup the printer with a computer and it will print the first time or two...on Friday. Then Sunday rolls around and the iPads are acting like there is no printer connected to the network for AirPrinting. I'm really not sure what to do...and we haven't been able to get it to work one week. 😕 Please help!

**Comment by petereit** [comment]
Make sure your AirPrint label printer is connected to the same network as your iPads. You can confirm this before you even launch the CheckinAir app. Just open Safari on your iPad, tap the Share icon, select print and look for your label printer in the AirPrint selection dialog. If you don’t see your label printer, you have a network issue. Either your printer and iPad aren’t on the same network or your label printer is not correctly configured.

**Comment by pastorjosh5142** [comment]
Checked this AM and the printer is showing up for AirPrint on iOS devices...but not being recognized by Checkin Air. 😕 

Josh Yates
Lead Pastor
248-420-6323
www.gcc4him.org

**Comment by petereit** [comment]
Are you using Breeze’s utility to check for printers? That utility assumes you’re using Dymo printers connected to a PC that serves as a printer controller. If you’re using that utility, it will never show AirPrint-connected label printers.

**Comment by petereit** [comment]
That is correct. Breeze will never find a printer when you first sign in, because there aren’t any printers available the way Breeze expects to find them (Dymo printers attached to a centralized PC acting as a print server.)

The Checkin Air app isn’t even aware of any printers when you first sign in. It isn’t until you check in your first person that it displays the AirPrint dialog, lets you select your Brother printer, then stores that selection for all subsequent checkins.

**Comment by pastorjosh5142** [comment]
Checkin Air is not recognizing the printer on the iPads. It is recognizing the printer through my iPhone X. Would you have any suggestions? I’m a pretty techy guy...and I cannot get this to work. 

Josh Yates
Lead Pastor
248-420-6323
www.gcc4him.org

**Comment by petereit** [comment]
If your phone sees it in the CheckinAir app, but an iPad on the same network does not, it would appear to be an issue with the iPad.

**Comment by pastorjosh5142** [comment]
Okay…

The iPads both see the printer. The printer shows up in Safari as a printer that can be printed to.

The app is not even attempting to AirPrint on either iPad 4 that we purchased for this setup.  they are both running iOS 10.3.3.

My iPhone X will print to the printer using the app. It is running iOS 12.0.1.

Is there a setting in the app that could be changed in order for the printer to work? I have uninstalled, re-installed, closed the app, re-opened the app. I will be resetting the iPads as well.  These iPads will print to an AirPrint printer…the app isn’t recognizing it. In fact, when the iPads were first installed, they recognized the printer and printed the correct labels. They have printed to them before…and now they will not. After the system wasn’t used for a couple weeks (we were testing), they don’t want to print. That’s why I installed a second node for a Google Wifi mesh network. The network signal is strong now.

Could the app not have all functionality in 10.3.3? 

I appreciate any information/help/guidance you can give me. We’ve invested money into this setup and I’m just trying to get it to work. 😀 

Josh Yates
Lead Pastor
www.gcc4him.org
Cell 248-420-6323

**Comment by petereit** [comment]
I’m sorry for the frustration. The printing part of the app has been the same since I first released it back on iOS 7. It just utilizes Apple’s basic AirPrint functions.

If it works on one of your devices it should work on all of your devices.

**Comment by triegler** [comment]
Hi Mark and Josh,

We are having the exact same issue - 4th Gen iPads on iOS 10.3.3 not seeing either a QL-810W or the QL-820NWB from within the app. We use Ubiquiti wireless infrastructure, and I've verified everything is on the same SSID. We also can print directly to the printers via Safari, or through Checkin Air via other iOS devices (iPhone 6+, iPhone 7, iPad Air), but all are running newer versions of iOS. There is a known bug for Brother printers for AirPrint that requires using their app, and I'm fairly sure that this is not related (link: https://support.brother.com/g/b/faqend.aspx?c=us&lang=en&prod=lpql810weus&faqid=faqp00100306_000), as it has to do with iOS 10.1 / 10.2.

My next step is to check the web interface on the device and see if there is something there. Otherwise, looks like we may have to invest in some newer iPads.

Either way, thank you for the application!

~Tim

**Comment by petereit** [comment]
Something important to consider when checking if the printer is visible from the app: 

The Breeze system itself doesn’t know anything about AirPrint printers. So if you’re using Breeze’s “Check Printer” function, it’s never going to see the AirPrint printers. (Breeze has built some new functionality in their beta version that will resolve that issue.)

The only way to check if the CheckinAir app “sees” the AirPrint printers is to print a label. When you print the first label, the app will display the AirPrint dialog and allow you to choose an AirPrint label printer. Once you’ve selected a printer, the app will use that printer as the default from that iPad. 

Mark

**Comment by triegler** [comment]
UPDATE:

AirPrint is working! It was not a problem with the iPad 4's on iOS 10.3.3. We completely reconfigured all wireless, and this is what ended up working for us:
* Class C subnet (no supernet)
* IGMP snooping enabled
* Separate WLAN for only the Check In stations / printers (no other AirPrint devices)

Thank you again Mark for the application, and your support! We appreciate it tremendously!

~Tim

**Comment by petereit** [comment]
Awesome! Thanks for the update!
