### ISSUE TITLE
Camera feature at check in not working

### ISSUE THREAD

**Issue by jrossnagle** [petereit/CheckinAir#7]
When I click on the picture placeholders menu appears and when I choose use camera to take picture it boots me out of the app.

**Comment by petereit** [comment]
The app wasn’t designed to support this feature. I have another issue I need to resolve so I’ll take a look at the picture functionality while I’m in the app this week.

**Comment by petereit** [comment]
I don't get any kind of menu when I tap the picture placeholder. Can you give me step-by-step instructions how to duplicate this issue?

**Comment by jrossnagle** [comment]
[cid:image001.png@01D3BB8F.ED1944D0]

Jennifer Rossnagle[cid:image002.png@01D3BB8F.ED1944D0]
Office Administrator
Hope Community Church
2425 Black Lake Blvd. SW
Olympia, WA 98512
360-357-3235
[/Users/jenniferrossnagle/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_479044437]

**Comment by jrossnagle** [comment]
I open the event through the app, then tap once on the placeholder and the menu comes up. See screen shots I just sent.

Jennifer Rossnagle
Office Administrator
Hope Community Church
2425 Black Lake Blvd. SW
Olympia, WA 98512
360-357-3235
[/Users/jenniferrossnagle/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1805840398]

**Comment by petereit** [comment]
Thank you for that additional information!

I designed the app to work with accounts that are set up with checkin authorization only. They don't have the ability to create photos, which is why I wasn't able to duplicate that issue.

I logged in using an administrative account and was able to duplicate the issue. I can certainly see how handy it would be to be able to use your iPad/iPhone camera to add photos! In order to make this work, I'll need to program my app to request permission to use the camera. (This is why it's bombing.) 

As a workaround, you could log into Breeze in Safari and open your event there. This would allow you to take pictures, but it wouldn't allow you to print to your AirPrint label printer. You'd have to switch to Safari to take pictures, and switch back to my CheckinAir app to check in kids and get labels printed. Clunky for sure, but it can get you by for now.

I hope to find some time this weekend to work on updates to the app. I have one critical fix that will take priority, but if I have time, I'll see if I can add this functionality.

**Comment by petereit** [comment]
I have resolved the issue by adding camera and photo library access requests to the app. Version 1.32 has just been pushed to the app store and is awaiting approval and release by Apple.

**Comment by jrossnagle** [comment]
Wow!! Thank you so much!!

Thanks, Jennifer
Sent from my iPhone

On Mar 16, 2018, at 2:12 PM, Mark Petereit <notifications@github.com<mailto:notifications@github.com>> wrote:


I have resolved the issue by adding camera and photo library access requests to the app. Version 1.32 has just been pushed to the app store and is awaiting approval and release by Apple.
